[log]
level = "info"

[http]
address = "0.0.0.0:8080"
force_https = true

[https]
address = "0.0.0.0:8443"
cert = "local/cert/edgee.pem"
key = "local/cert/edgee.key"

[monitor]
address = "0.0.0.0:8222"

[[destinations.data_collection]]
name = "amplitude"
component = "local/wasm/amplitude.wasm"
credentials.amplitude_api_key = "..."

[[destinations.data_collection]]
name = "google analytics"
component = "local/wasm/ga.wasm"
credentials.ga_measurement_id = "..."

[[destinations.data_collection]]
name = "segment"
component = "local/wasm/segment.wasm"
credentials.segment_project_id = "..."
credentials.segment_write_key = "..."

[[routing]]
domain = "demo.edgee.dev"

[[routing.backends]]
name = "demo"
default = true
address = "localhost:9000"
enable_ssl = false
