name: Run tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2024-10-15
          components: rustfmt
      - uses: clechasseur/rs-fmt-check@v2
        with:
          toolchain: nightly-2024-10-15
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: wearerequired/lint-action@master
        with:
          clippy: true

  test:
    name: cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        rust: ["nightly", "stable"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: make ci.test

  coverage:
    name: coverage & coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: make test.coverage.lcov
      - uses: coverallsapp/github-action@v2

